# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "CogReader",
    "read_geotiff",
]

@typing.final
class CogReader:
    r"""
    Python class interface to a Cloud-optimized GeoTIFF reader (image-tiff backend).
    
    Parameters
    ----------
    path : str
        The path to the file, or a url to a remote file.
    
    Returns
    -------
    reader : cog3pio.CogReader
        A new CogReader instance for decoding GeoTIFF files.
    
    Examples
    --------
    Read a GeoTIFF from a HTTP url into a DLPack tensor:
    
    >>> import numpy as np
    >>> from cog3pio import CogReader
    ...
    >>> cog = CogReader(
    ...     path="https://github.com/rasterio/rasterio/raw/1.5.0/tests/data/RGBA.uint16.tif"
    ... )
    >>> array: np.ndarray = np.from_dlpack(cog)
    >>> array.shape
    (4, 411, 634)
    >>> array.dtype
    dtype('uint16')
    """
    def __new__(cls, path: builtins.str) -> CogReader: ...
    @staticmethod
    def __dlpack_device__() -> tuple[builtins.int, builtins.int]:
        r"""
        Get device type and device ID in DLPack format.
        
        Meant for use by ``from_dlpack()``.
        
        Returns
        -------
        device : (int, int)
            A tuple (``device_type``, ``device_id``) in DLPack format.
        """
    def xy_coords(self) -> tuple[numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float64]]:
        r"""
        Get list of x and y coordinates.
        
        Determined based on an Affine transformation matrix built from the
        `ModelPixelScaleTag` and `ModelTiepointTag` TIFF tags. Note that non-zero
        rotation (set by `ModelTransformationTag` is currently unsupported.
        
        Returns
        -------
        coords : (numpy.ndarray, numpy.ndarray)
           A tuple (x_coords, y_coords) of numpy.ndarray objects representing the
           GeoTIFF's x- and y-coordinates.
        """

def read_geotiff(path: builtins.str) -> numpy.typing.NDArray[numpy.float32]:
    r"""
    Read a GeoTIFF file from a path on disk or a url into an ndarray.
    
    Parameters
    ----------
    path : str
        The path to the file, or a url to a remote file.
    
    Returns
    -------
    array : numpy.ndarray
        3D array of shape (band, height, width) containing the GeoTIFF pixel data.
    
    Raises
    ------
    ValueError
        If a TIFF which has a non-float32 dtype is passed in. Please use
        `cog3pio.CogReader` for reading TIFFs with other dtypes (e.g. uint16).
    
    Examples
    --------
    Read a GeoTIFF from a HTTP url into a numpy.ndarray:
    
    >>> from cog3pio import read_geotiff
    ...
    >>> array = read_geotiff("https://github.com/pka/georaster/raw/v0.2.0/data/tiff/float32.tif")
    >>> array.shape
    (1, 20, 20)
    """

