# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.com/platform/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: "ubuntu-26.04"
  tools:
    python: "miniforge3-25.11"
    rust: "1.91"
  jobs:
    create_environment:
      # Patch nvtiff.h (v0.7.0) to add missing enum tag
      - export CONDA_PREFIX="$CONDA_ENVS_PATH/$CONDA_DEFAULT_ENV";
        unset CONDA_DEFAULT_ENV;
        mamba env update --prefix "$CONDA_PREFIX" --file docs/environment.yml;
        mamba list;
        sed --in-place "s/nvtiffTagDataType type/enum nvtiffTagDataType type/g" $CONDA_PREFIX/include/nvtiff.h
    install:
      - export CONDA_PREFIX="$CONDA_ENVS_PATH/$CONDA_DEFAULT_ENV";
        ln -s $CONDA_PREFIX/include/nvtiff.h $CONDA_PREFIX/targets/x86_64-linux/include/nvtiff.h;
        ln -s $CONDA_PREFIX/include/nvtiff_version.h $CONDA_PREFIX/targets/x86_64-linux/include/nvtiff_version.h;
        ln -s $CONDA_PREFIX/lib/libnvtiff.so $CONDA_PREFIX/targets/x86_64-linux/lib/libnvtiff.so;
        RUSTFLAGS="-L$CONDA_PREFIX/targets/x86_64-linux/lib"
        BINDGEN_EXTRA_CLANG_ARGS="-I $CONDA_PREFIX/targets/x86_64-linux/include"
        MATURIN_PEP517_ARGS="--features cuda,pyo3"
        mamba run --prefix "$CONDA_PREFIX" pip install . --group docs
      - pip list
    post_install:
      - zensical --version
    build:
      html:
        - "zensical build"
        - "ls -lh site/"
    post_build:
      - "mkdir --parents $READTHEDOCS_OUTPUT/html/"
      - "cp --recursive site/* $READTHEDOCS_OUTPUT/html/"

conda:
  environment: docs/environment.yml
