# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.com/platform/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: "ubuntu-24.04"
  tools:
    nodejs: "23"
    python: "3.12"
    rust: "1.86"
  jobs:
    post_install:
      - npm install -g mystmd
      - myst --version
    pre_build:
      - "cd docs/"
      - "sphinx-build --builder myst . _build/myst-asts"
    build:
      html:
        - "cd docs/"
        - "myst build --html"
    post_build:
      - "mkdir --parents $READTHEDOCS_OUTPUT/html/"
      - "mv docs/_build/html/* $READTHEDOCS_OUTPUT/html/"

# Build documentation in the "docs/" directory with Sphinx
# sphinx:
#   configuration: docs/conf.py
#   # You can configure Sphinx to use a different builder, for instance use the dirhtml builder for simpler URLs
#   builder: "myst" # https://jupyter-book.github.io/sphinx-ext-mystmd/include-sphinx
#   # Fail on all warnings to avoid broken references
#   # fail_on_warning: true

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.com/platform/stable/guides/reproducible-builds.html
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
