# Run linters
#
# Lint Rust code using cargo clippy, and GitHub Actions workflows using zizmor. Apply
# static analysis rules to catch common mistakes and improves code style.

name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ["main"]

permissions: {}

# Make sure CI fails on all warnings, including Clippy lints
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false

      - name: Run Clippy
        run: cargo clippy --all-targets

  format_check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Run Rustfmt
        run: cargo fmt --check -- --config imports_granularity=Module,group_imports=StdExternalCrate

  stubtest:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"

      - name: Build wheels
        uses: PyO3/maturin-action@04ac600d27cdf7a9a280dadf7147097c42b757ad # v1.50.1
        with:
          target: x86_64
          args: --locked --features cuda,pyo3 --out dist
          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
          manylinux: "2_28"
          before-script-linux: |
            # Install nvTIFF and clang-devel
            if command -v dnf &> /dev/null; then
              # https://developer.nvidia.com/nvtiff-0-6-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Rocky&target_version=8&target_type=rpm_network
              dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel8/${{ matrix.platform.arch || 'x86_64' }}/cuda-rhel8.repo
              dnf clean all
              dnf install -y clang-devel cuda-crt-13-0 cuda-cudart-devel-13-0 nvtiff-cuda-13-0.6.0.* libnvtiff0-cuda-13-0.6.0.*
              # Patch nvtiff.h (v0.6.0) to add missing enum tag
              sed --in-place "s/nvtiffTagDataType type/enum nvtiffTagDataType type/g" /usr/include/nvtiff.h
            fi

      - name: Run mypy stubtest
        run: |
          set -e
          python3 -m venv .venv
          source .venv/bin/activate
          pip install cog3pio --no-index --no-deps --find-links dist --force-reinstall -vv
          pip install cog3pio[tests]
          stubtest cog3pio --ignore-missing-stub --ignore-disjoint-bases

  zizmor:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@f94ec6bedd8674c4426838e6b50417d36b6ab231 # v5.3.1

      - name: Run zizmor 🌈
        run: uvx zizmor --color=always .
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
